apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-helloworld-python-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-helloworld-python-simple
  template:
    metadata:
      labels:
        app: http-helloworld-python-simple
    spec:
      containers:
        - name: http-helloworld-python-simple
          image: python:3.12-slim
          command: ["python3", "-u", "-c"]
          args:
            - |
              import socket;
              s=socket.socket();s.bind(('',8080));s.listen();
              print('listening');c,a=s.accept();
              c.send(b'HTTP/1.1 200 OK\r\n\r\nHello, World!');c.close()
          ports:
            - containerPort: 8080
